name: stunt-car-remake # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.00.02' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Remake of the Stunt Car video game
description: |
   Remake of the Stunt Car video game

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  stunt-car-remake_icon.png
title: Stunt Car Remake

apps:
  stunt-car-remake:
    command: stunt-car-remake
parts:
  stunt-car-remake:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      stunt-car-remake: build/
      stunt-car-remake.1: man/man1/

architectures:
  - build-on: amd64

